version: 2

updates:
  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    assignees:
      - "tamaco489"
    commit-message:
      prefix: "frontend"
      prefix-development: "frontend(dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Major version updates require manual review
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      # Group React ecosystem updates
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
      # Group Next.js ecosystem updates
      nextjs-ecosystem:
        patterns:
          - "next*"
          - "@next/*"
      # Group TypeScript ecosystem updates
      typescript-ecosystem:
        patterns:
          - "typescript"
          - "@types/*"
      # Group linting tools
      linting-tools:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier"
      # Group TailwindCSS ecosystem
      tailwind-ecosystem:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
          - "postcss*"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    assignees:
      - "tamaco489"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
