// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package gen_sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	AddArticleTag(ctx context.Context, db DBTX, arg AddArticleTagParams) error
	AddArticleTagBulk(ctx context.Context, db DBTX, arg AddArticleTagBulkParams) error
	CheckArticleHasTag(ctx context.Context, db DBTX, arg CheckArticleHasTagParams) (bool, error)
	CountArticles(ctx context.Context, db DBTX) (int64, error)
	CountArticlesByCategory(ctx context.Context, db DBTX, categoryID uuid.NullUUID) (int64, error)
	CountArticlesByMonth(ctx context.Context, db DBTX, arg CountArticlesByMonthParams) (int64, error)
	CountArticlesByTagID(ctx context.Context, db DBTX, tagID uuid.UUID) (int64, error)
	CountSearchArticles(ctx context.Context, db DBTX, query sql.NullString) (int64, error)
	CreateArticle(ctx context.Context, db DBTX, arg CreateArticleParams) (Article, error)
	CreateArticleSEOMetadata(ctx context.Context, db DBTX, arg CreateArticleSEOMetadataParams) (ArticleSeoMetadatum, error)
	CreateCategory(ctx context.Context, db DBTX, arg CreateCategoryParams) (Category, error)
	CreateTag(ctx context.Context, db DBTX, arg CreateTagParams) (Tag, error)
	DecrementTagUsageCount(ctx context.Context, db DBTX, id uuid.UUID) error
	DeleteArticle(ctx context.Context, db DBTX, id uuid.UUID) error
	DeleteArticleSEOMetadata(ctx context.Context, db DBTX, articleID uuid.UUID) error
	DeleteCategory(ctx context.Context, db DBTX, id uuid.UUID) error
	DeleteTag(ctx context.Context, db DBTX, id uuid.UUID) error
	GetArticle(ctx context.Context, db DBTX, id uuid.UUID) (Article, error)
	GetArticleBySlug(ctx context.Context, db DBTX, slug string) (Article, error)
	GetArticleBySlugWithRelations(ctx context.Context, db DBTX, slug string) (GetArticleBySlugWithRelationsRow, error)
	GetArticleSEOMetadata(ctx context.Context, db DBTX, articleID uuid.UUID) (ArticleSeoMetadatum, error)
	GetArticleWithRelations(ctx context.Context, db DBTX, id uuid.UUID) (GetArticleWithRelationsRow, error)
	GetArticleWithTags(ctx context.Context, db DBTX, id uuid.UUID) ([]GetArticleWithTagsRow, error)
	GetCategory(ctx context.Context, db DBTX, id uuid.UUID) (Category, error)
	GetCategoryBySlug(ctx context.Context, db DBTX, slug string) (Category, error)
	GetTag(ctx context.Context, db DBTX, id uuid.UUID) (Tag, error)
	GetTagBySlug(ctx context.Context, db DBTX, slug string) (Tag, error)
	IncrementArticleViewCount(ctx context.Context, db DBTX, id uuid.UUID) error
	IncrementTagUsageCount(ctx context.Context, db DBTX, id uuid.UUID) error
	ListArticleIDsByTagID(ctx context.Context, db DBTX, tagID uuid.UUID) ([]uuid.UUID, error)
	ListArticles(ctx context.Context, db DBTX, arg ListArticlesParams) ([]Article, error)
	ListArticlesByCategory(ctx context.Context, db DBTX, arg ListArticlesByCategoryParams) ([]Article, error)
	ListArticlesByMonth(ctx context.Context, db DBTX, arg ListArticlesByMonthParams) ([]Article, error)
	ListArticlesByStatus(ctx context.Context, db DBTX, arg ListArticlesByStatusParams) ([]Article, error)
	ListArticlesByTagID(ctx context.Context, db DBTX, arg ListArticlesByTagIDParams) ([]Article, error)
	ListArticlesWithAllRelations(ctx context.Context, db DBTX, arg ListArticlesWithAllRelationsParams) ([]ListArticlesWithAllRelationsRow, error)
	ListArticlesWithCategory(ctx context.Context, db DBTX, arg ListArticlesWithCategoryParams) ([]ListArticlesWithCategoryRow, error)
	ListArticlesWithSEOMetadata(ctx context.Context, db DBTX, arg ListArticlesWithSEOMetadataParams) ([]ListArticlesWithSEOMetadataRow, error)
	ListCategories(ctx context.Context, db DBTX) ([]Category, error)
	ListPopularArticles(ctx context.Context, db DBTX, limit int32) ([]Article, error)
	ListPopularTags(ctx context.Context, db DBTX, limit int32) ([]Tag, error)
	ListRecentArticles(ctx context.Context, db DBTX, limit int32) ([]Article, error)
	ListTags(ctx context.Context, db DBTX) ([]Tag, error)
	ListTagsByArticleID(ctx context.Context, db DBTX, articleID uuid.UUID) ([]Tag, error)
	RemoveAllArticleTags(ctx context.Context, db DBTX, articleID uuid.UUID) error
	RemoveArticleTag(ctx context.Context, db DBTX, arg RemoveArticleTagParams) error
	SearchArticles(ctx context.Context, db DBTX, arg SearchArticlesParams) ([]Article, error)
	UpdateArticle(ctx context.Context, db DBTX, arg UpdateArticleParams) (Article, error)
	UpdateArticleSEOMetadata(ctx context.Context, db DBTX, arg UpdateArticleSEOMetadataParams) (ArticleSeoMetadatum, error)
	UpdateArticleStatus(ctx context.Context, db DBTX, arg UpdateArticleStatusParams) (Article, error)
	UpdateCategory(ctx context.Context, db DBTX, arg UpdateCategoryParams) (Category, error)
	UpdateCategoryArticleCount(ctx context.Context, db DBTX, arg UpdateCategoryArticleCountParams) error
	UpdateTag(ctx context.Context, db DBTX, arg UpdateTagParams) (Tag, error)
	UpdateTagUsageCount(ctx context.Context, db DBTX, arg UpdateTagUsageCountParams) error
	UpsertArticleSEOMetadata(ctx context.Context, db DBTX, arg UpsertArticleSEOMetadataParams) (ArticleSeoMetadatum, error)
}

var _ Querier = (*Queries)(nil)
