openapi: 3.0.0
info:
  title: article api
  description: |
    tamaco-blog 記事管理システムのバックエンドAPIサービス。
    ブログ記事のCRUD操作、カテゴリ・タグの管理、
    記事関連の各種操作を提供するRESTful APIです。
  version: 1.0.0
servers:
  - url: "http://localhost:{port}/article/"
    description: dev
    variables:
      port:
        default: "8080"
  - url: "https://api.<stg-domain-name>/article/"
    description: stg
  - url: "https://api.<prd-domain-name>/article/"
    description: prd

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /v1/health:
    get:
      tags:
        - healthcheck
      summary: ヘルスチェックAPI
      description: APIが正常に動作しているかを確認します。
      operationId: healthcheck
      responses:
        "200":
          description: APIサービスが正常に稼働中であることを示すレスポンス
          content:
            application/json:
              schema:
                $ref: "./api/responses/HealthCheck.yaml"
      security: [] # healthcheckでは認証を必要としないため
