openapi: 3.0.0
info:
  title: article api
  description: |
    tamaco-blog 記事管理システムのバックエンドAPIサービス。
    ブログ記事のCRUD操作、カテゴリ・タグの管理、
    記事関連の各種操作を提供するRESTful APIです。
  version: 1.0.0
servers:
  - url: "http://localhost:{port}/article/"
    description: dev
    variables:
      port:
        default: "8080"
  - url: "https://api.<stg-domain-name>/article/"
    description: stg
  - url: "https://api.<prd-domain-name>/article/"
    description: prd

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /v1/health:
    get:
      tags:
        - healthcheck
      summary: ヘルスチェックAPI
      description: APIが正常に動作しているかを確認します。
      operationId: healthcheck
      responses:
        "200":
          description: APIサービスが正常に稼働中であることを示すレスポンス
          content:
            application/json:
              schema:
                $ref: "./api/responses/HealthCheck.yaml"
      security: [] # healthcheckでは認証を必要としないため

  # 記事系API
  /v1/articles:
    $ref: "./api/paths/articles.yaml#/~1v1~1articles"
  /v1/articles/{article_id}:
    $ref: "./api/paths/articles.yaml#/~1v1~1articles~1{article_id}"
  /v1/articles/{article_id}/publish:
    $ref: "./api/paths/articles.yaml#/~1v1~1articles~1{article_id}~1publish"
  /v1/articles/{article_id}/views:
    $ref: "./api/paths/articles.yaml#/~1v1~1articles~1{article_id}~1views"
  /v1/articles/popular:
    $ref: "./api/paths/articles.yaml#/~1v1~1articles~1popular"
  /v1/articles/recent:
    $ref: "./api/paths/articles.yaml#/~1v1~1articles~1recent"
  /v1/articles/archive/{year}/{month}:
    $ref: "./api/paths/articles.yaml#/~1v1~1articles~1archive~1{year}~1{month}"

  # カテゴリ系API
  /v1/categories:
    $ref: "./api/paths/categories.yaml#/~1v1~1categories"
  /v1/categories/{category_id}:
    $ref: "./api/paths/categories.yaml#/~1v1~1categories~1{category_id}"
  /v1/categories/{category_id}/articles:
    $ref: "./api/paths/categories.yaml#/~1v1~1categories~1{category_id}~1articles"

  # タグ系API
  /v1/tags:
    $ref: "./api/paths/tags.yaml#/~1v1~1tags"
  /v1/tags/{tag_id}:
    $ref: "./api/paths/tags.yaml#/~1v1~1tags~1{tag_id}"
  /v1/tags/{tag_id}/articles:
    $ref: "./api/paths/tags.yaml#/~1v1~1tags~1{tag_id}~1articles"

  # 検索API
  /v1/search:
    $ref: "./api/paths/search.yaml#/~1v1~1search"
