name: Dependabot Auto-Merge

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Detect change type
        id: detect-changes
        run: |
          if [[ "${{ github.event.pull_request.title }}" == *"frontend"* ]] || \
            [[ "${{ contains(github.event.pull_request.changed_files, 'frontend/') }}" == "true" ]]; then
            echo "type=frontend" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.pull_request.title }}" == *"backend"* ]] || \
              [[ "${{ contains(github.event.pull_request.changed_files, 'backend/') }}" == "true" ]]; then
            echo "type=backend" >> $GITHUB_OUTPUT
          else
            echo "type=other" >> $GITHUB_OUTPUT
          fi

      # Frontend validation
      - name: Setup Node.js
        if: steps.detect-changes.outputs.type == 'frontend'
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install frontend dependencies
        if: steps.detect-changes.outputs.type == 'frontend'
        run: |
          cd frontend
          npm ci

      - name: Run frontend security audit
        if: steps.detect-changes.outputs.type == 'frontend'
        run: |
          cd frontend
          npm audit --audit-level=moderate

      - name: Run frontend lint
        if: steps.detect-changes.outputs.type == 'frontend'
        run: |
          cd frontend
          npm run lint

      - name: Run frontend type check
        if: steps.detect-changes.outputs.type == 'frontend'
        run: |
          cd frontend
          npm run typecheck

      - name: Run frontend build
        if: steps.detect-changes.outputs.type == 'frontend'
        run: |
          cd frontend
          npm run build

      # Backend validation
      - name: Setup Go
        if: steps.detect-changes.outputs.type == 'backend'
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.6"
          cache-dependency-path: "backend/api/article/go.sum"

      - name: Download Go dependencies
        if: steps.detect-changes.outputs.type == 'backend'
        run: |
          cd backend/api/article
          go mod download

      # - name: Run Go security check
      #   if: steps.detect-changes.outputs.type == 'backend'
      #   # TODO: Temporarily disabled due to Go version mismatch
      #   # Current: go.mod requires Go 1.25.0 (unreleased), but actions/setup-go@v5 falls back to Go 1.24
      #   # Enable this step once actions/setup-go@v5 supports Go 1.25 or when go.mod is updated to stable version
      #   run: |
      #     cd backend/api/article
      #     go install golang.org/x/vuln/cmd/govulncheck@latest
      #     govulncheck ./...

      - name: Run Go lint
        if: steps.detect-changes.outputs.type == 'backend'
        run: |
          cd backend/api/article
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run --timeout 3m

      - name: Run Go build
        if: steps.detect-changes.outputs.type == 'backend'
        run: |
          cd backend/api/article
          go build -v -o build/article_api ./cmd

      - name: Run Go tests
        if: steps.detect-changes.outputs.type == 'backend'
        run: |
          cd backend/api/article
          go test -v -race -cover ./... || echo "No tests found yet"

      - name: Check Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Auto-merge patch updates
        if: |
          steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          steps.metadata.outputs.dependency-type == 'direct:development'
        run: |
          echo "✅ Auto-merging patch update or dev dependency"
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on security update
        if: contains(steps.metadata.outputs.dependency-names, 'security')
        run: |
          gh pr comment "$PR_URL" --body "🔒 This appears to be a security update. Please review carefully before merging."
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
