name: PR Backend Quality Checks

on:
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/pr-backend-checks.yaml"

jobs:
  security-check:
    name: Security Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/api/article

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.6"
          cache-dependency-path: "backend/api/article/go.sum"

      - name: Download dependencies
        run: go mod download

      - name: Run govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

      - name: Check for Go module vulnerabilities
        run: |
          echo "🔍 Checking for known vulnerabilities in dependencies"
          go list -json -deps ./... | grep '"Module"' | sort -u || true

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/api/article

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.6"
          cache-dependency-path: "backend/api/article/go.sum"

      - name: Download dependencies
        run: go mod download

      - name: Check cyclomatic complexity
        run: |
          go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
          gocyclo -over 15 . || echo "ℹ️ Cyclomatic complexity check completed"

      - name: Check code coverage potential
        run: |
          echo "📊 Analyzing test coverage potential"
          go test -coverprofile=coverage.out ./... || echo "No tests to analyze yet"
          if [ -f coverage.out ]; then
            go tool cover -func=coverage.out || true
          fi

      - name: Check for ineffective assignments
        run: |
          go install github.com/gordonklaus/ineffassign@latest
          ineffassign ./...

      - name: Check for unused variables
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./... || echo "ℹ️ Static analysis completed"

  dependency-analysis:
    name: Dependency Analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/api/article

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.6"
          cache-dependency-path: "backend/api/article/go.sum"

      - name: Download dependencies
        run: go mod download

      - name: Check for outdated dependencies
        run: |
          echo "📦 Checking for outdated Go modules"
          go list -u -m all || true

      - name: Verify go.mod tidiness
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum || {
            echo "❌ go.mod or go.sum files are not tidy"
            echo "Please run 'go mod tidy' and commit the changes"
            exit 1
          }

      - name: Check module licenses
        run: |
          echo "📄 Analyzing module licenses"
          go list -m all | head -10 || true
          echo "ℹ️ License analysis completed"
