name: PR Frontend Quality Checks

on:
  pull_request:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/pr-frontend-checks.yaml"

jobs:
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level=moderate

  bundle-analysis:
    name: Bundle Analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Analyze bundle composition without build
        run: |
          echo "📊 Analyzing bundle composition and dependencies"
          echo "Checking for potential bundle size issues..."

      - name: Check for large dependencies
        run: |
          echo "📦 Checking for large dependencies"
          npm list --depth=0 --long | head -20 || true

      - name: Analyze package sizes
        run: |
          echo "📏 Analyzing individual package sizes"
          npx size-limit --why || echo "size-limit not configured yet"

  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Check for outdated dependencies
        run: |
          npm outdated || true
          echo "ℹ️ Outdated dependencies check completed"

      - name: Check for unused dependencies
        run: |
          npx depcheck || true
          echo "ℹ️ Unused dependencies check completed"
