name: PR Frontend Quality Checks

on:
  pull_request:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/pr-frontend-checks.yaml"

jobs:
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level=moderate

  bundle-analysis:
    name: Bundle Analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Build for analysis
        run: npm run build
        env:
          ANALYZE: true

      - name: Check bundle size
        run: |
          echo "📦 Bundle analysis completed"
          echo "Check the build output for bundle size information"

  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Check for outdated dependencies
        run: |
          npm outdated || true
          echo "ℹ️ Outdated dependencies check completed"

      - name: Check for unused dependencies
        run: |
          npx depcheck || true
          echo "ℹ️ Unused dependencies check completed"
